version: '3.8'

services:
  mediamtx:
    image: bluenviron/mediamtx
    container_name: mediamtx
    ports:
      - "1935:1935"
      - "8888:8888"
      - "8554:8554"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./assets/standby_compatible.mp4:/opt/mediamtx/standby.mp4
    restart: unless-stopped

  tv-orchestrator:
    build: .
    container_name: tv-orchestrator
    ports:
      - "9001:9001"
    volumes:
      - ./data:/app/data             # Persistencia de base de datos
      - ./configs:/app/configs       # Recetas de navegación e interacción
      - ./assets:/app/assets         # Medios locales
      - /dev/shm:/dev/shm            # RAMDisk para almacenamiento temporal del streaming
    depends_on:
      - mediamtx
    restart: unless-stopped